export default [
  {
    version: "4.4.0",
    objects: [
      {
        type: "path",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 300,
        top: 250,
        width: 191,
        height: 191,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 0.52,
        scaleY: 0.52,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        customType: "shape",
        path: [
          ["M", 4.5, 195.5],
          ["L", 40.3125, 4.5],
          ["L", 159.68751, 4.5],
          ["L", 195.5, 195.5],
          ["L", 4.500010000000003, 195.5],
          ["z"],
        ],
      },
      {
        type: "textbox",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 269.53,
        top: 251.18,
        width: 160.94,
        height: 97.63,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        text: "내용을 입력하세요",
        fontSize: 40,
        fontWeight: 400,
        fontFamily: "Gamja Flower",
        fontStyle: "normal",
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "left",
        textBackgroundColor: "",
        charSpacing: 0,
        path: null,
        minWidth: 20,
        splitByGrapheme: false,
        customType: "textbox",
        styles: {},
      },
    ],
    background: "white",
  },
];
