export default [
  {
    version: "4.4.0",
    objects: [
      {
        type: "ellipse",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 112,
        top: 197.57,
        width: 193,
        height: 183.81,
        fill: "#e8dd73",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 0.78,
        scaleY: 0.78,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        customType: "shape",
      },
      {
        type: "textbox",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 295.5,
        top: 258.18,
        width: 335.77,
        height: 45.2,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        text: "sample",
        fontSize: "40",
        fontWeight: 400,
        fontFamily: "Jua",
        fontStyle: "normal",
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "left",
        textBackgroundColor: "",
        charSpacing: 0,
        path: null,
        minWidth: 20,
        splitByGrapheme: false,
        customType: "textbox",
        styles: {},
      },
    ],
    background: "white",
  },
];
