export default [
  {
    version: "4.4.0",
    objects: [
      {
        type: "path",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 112,
        top: 197.57,
        width: 193,
        height: 183.81,
        fill: "#1d1bce",
        stroke: "#000",
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 0.78,
        scaleY: 0.78,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        customType: "shape",
        path: [
          ["M", 3.5, 78.30402],
          ["L", 99.99989, 8.095129999999997],
          ["L", 196.5, 78.30402],
          ["L", 159.6404, 191.90488],
          ["L", 40.359700000000004, 191.90488],
          ["L", 3.499990000000004, 78.30402],
          ["z"],
        ],
      },
      {
        type: "textbox",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 295.5,
        top: 258.18,
        width: 335.77,
        height: 45.2,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        text: "sample 1",
        fontSize: "40",
        fontWeight: 400,
        fontFamily: "Jua",
        fontStyle: "normal",
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "left",
        textBackgroundColor: "",
        charSpacing: 0,
        path: null,
        minWidth: 20,
        splitByGrapheme: false,
        customType: "textbox",
        styles: {},
      },
    ],
    background: "white",
  },
  {
    version: "4.4.0",
    objects: [
      {
        type: "path",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 159.12,
        top: 246.78,
        width: 193.19,
        height: 193,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 0.58,
        scaleY: 0.58,
        angle: 45.77,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        customType: "shape",
        path: [
          ["M", 3.40717, 99.76839],
          ["L", 100, 3.5],
          ["L", 196.59283, 99.76839],
          ["L", 148.29640999999998, 99.76839],
          ["L", 148.29640999999998, 196.5],
          ["L", 51.703579999999974, 196.5],
          ["L", 51.703579999999974, 99.76839],
          ["L", 3.407159999999976, 99.76839],
          ["z"],
        ],
      },
      {
        type: "textbox",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 235.5,
        top: 230.18,
        width: 355.77,
        height: 79.1,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        text: "sample 2",
        fontSize: "70",
        fontWeight: "600",
        fontFamily: "Sunflower",
        fontStyle: "normal",
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "left",
        textBackgroundColor: "",
        charSpacing: 0,
        path: null,
        minWidth: 20,
        splitByGrapheme: false,
        customType: "textbox",
        styles: {},
      },
    ],
    background: "white",
  },
  {
    version: "4.4.0",
    objects: [
      {
        type: "path",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 57.5,
        top: 93.33,
        width: 192,
        height: 182.4,
        fill: "#e8dd73",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 0.59,
        scaleY: 0.59,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        customType: "shape",
        path: [
          ["M", 4.4675, 79.16554],
          ["L", 77.8055, 79.16554],
          ["L", 100.46750999999999, 9.494749999999996],
          ["L", 123.12952999999999, 79.16554],
          ["L", 196.46751, 79.16554],
          ["L", 137.13593, 122.22395999999999],
          ["L", 159.79911, 191.89475],
          ["L", 100.46751, 148.83515],
          ["L", 41.135920000000006, 191.89475],
          ["L", 63.79910000000001, 122.22395999999999],
          ["L", 4.467500000000008, 79.16554],
          ["z"],
        ],
      },
      {
        type: "textbox",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 205.8,
        top: 244.57,
        width: 302.75,
        height: 79.1,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        text: "sample 3",
        fontSize: "70",
        fontWeight: "600",
        fontFamily: "Noto Sans KR",
        fontStyle: "normal",
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "left",
        textBackgroundColor: "",
        charSpacing: 0,
        path: null,
        minWidth: 20,
        splitByGrapheme: false,
        customType: "textbox",
        styles: {},
      },
    ],
    background: "white",
  },
  {
    version: "4.4.0",
    objects: [
      {
        type: "textbox",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 112,
        top: 197.57,
        width: 193,
        height: 183.81,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        text: "sample",
        fontSize: "70",
        fontWeight: "600",
        fontFamily: "Noto Sans KR",
        fontStyle: "normal",
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "left",
        textBackgroundColor: "",
        charSpacing: 0,
        path: null,
        minWidth: 20,
        splitByGrapheme: false,
        customType: "textbox",
        styles: {},
      },
    ],
    background: "white",
  },
  {
    version: "4.4.0",
    objects: [
      {
        type: "ellipse",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 112,
        top: 197.57,
        width: 193,
        height: 183.81,
        fill: "#e8dd73",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 0.78,
        scaleY: 0.78,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        customType: "shape",
      },
      {
        type: "textbox",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 295.5,
        top: 258.18,
        width: 335.77,
        height: 45.2,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        text: "sample",
        fontSize: "40",
        fontWeight: 400,
        fontFamily: "Jua",
        fontStyle: "normal",
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "left",
        textBackgroundColor: "",
        charSpacing: 0,
        path: null,
        minWidth: 20,
        splitByGrapheme: false,
        customType: "textbox",
        styles: {},
      },
    ],
    background: "white",
  },
];
