export default [
  {
    version: "4.4.0",
    objects: [
      {
        type: "textbox",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 342.5,
        top: 256.18,
        width: 335.77,
        height: 45.2,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        text: "sample",
        fontSize: "40",
        fontWeight: 400,
        fontFamily: "Jua",
        fontStyle: "normal",
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "left",
        textBackgroundColor: "",
        charSpacing: 0,
        path: null,
        minWidth: 20,
        splitByGrapheme: false,
        customType: "textbox",
        styles: {},
      },
      {
        type: "path",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 169.5,
        top: 209.1,
        width: 193,
        height: 183.81,
        fill: "#1d1bce",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 0.78,
        scaleY: 0.78,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        customType: "shape",
        path: [
          ["M", 3.5, 78.30402],
          ["L", 99.99989, 8.095129999999997],
          ["L", 196.5, 78.30402],
          ["L", 159.6404, 191.90488],
          ["L", 40.359700000000004, 191.90488],
          ["L", 3.499990000000004, 78.30402],
          ["z"],
        ],
      },
    ],
    background: "white",
  },
  {
    version: "4.4.0",
    objects: [
      {
        type: "path",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 190.12,
        top: 247.78,
        width: 193.19,
        height: 193,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 0.58,
        scaleY: 0.58,
        angle: 45.77,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        customType: "shape",
        path: [
          ["M", 3.40717, 99.76839],
          ["L", 100, 3.5],
          ["L", 196.59283, 99.76839],
          ["L", 148.29640999999998, 99.76839],
          ["L", 148.29640999999998, 196.5],
          ["L", 51.703579999999974, 196.5],
          ["L", 51.703579999999974, 99.76839],
          ["L", 3.407159999999976, 99.76839],
          ["z"],
        ],
      },
      {
        type: "textbox",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 266.5,
        top: 231.18,
        width: 355.77,
        height: 79.1,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        text: "sample",
        fontSize: "70",
        fontWeight: "600",
        fontFamily: "Sunflower",
        fontStyle: "normal",
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "left",
        textBackgroundColor: "",
        charSpacing: 0,
        path: null,
        minWidth: 20,
        splitByGrapheme: false,
        customType: "textbox",
        styles: {},
      },
    ],
    background: "white",
  },
  {
    version: "4.4.0",
    objects: [
      {
        type: "path",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 119.5,
        top: 101.33,
        width: 192,
        height: 182.4,
        fill: "#e8dd73",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 0.59,
        scaleY: 0.59,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        customType: "shape",
        path: [
          ["M", 4.4675, 79.16554],
          ["L", 77.8055, 79.16554],
          ["L", 100.46750999999999, 9.494749999999996],
          ["L", 123.12952999999999, 79.16554],
          ["L", 196.46751, 79.16554],
          ["L", 137.13593, 122.22395999999999],
          ["L", 159.79911, 191.89475],
          ["L", 100.46751, 148.83515],
          ["L", 41.135920000000006, 191.89475],
          ["L", 63.79910000000001, 122.22395999999999],
          ["L", 4.467500000000008, 79.16554],
          ["z"],
        ],
      },
      {
        type: "textbox",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 267.8,
        top: 252.57,
        width: 302.75,
        height: 79.1,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        text: "sample",
        fontSize: "70",
        fontWeight: "600",
        fontFamily: "Noto Sans KR",
        fontStyle: "normal",
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "left",
        textBackgroundColor: "",
        charSpacing: 0,
        path: null,
        minWidth: 20,
        splitByGrapheme: false,
        customType: "textbox",
        styles: {},
      },
    ],
    background: "white",
  },
  {
    version: "4.4.0",
    objects: [
      {
        type: "path",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 160,
        top: 116,
        width: 193,
        height: 193,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1.92,
        scaleY: 1.92,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        customType: "shape",
        path: [
          ["M", 3.5, 60.02809],
          ["L", 60.0281, 3.5],
          ["L", 139.9719, 3.5],
          ["L", 196.5, 60.02809],
          ["L", 196.5, 139.9719],
          ["L", 139.9719, 196.5],
          ["L", 60.02810000000001, 196.5],
          ["L", 3.500000000000007, 139.9719],
          ["L", 3.500000000000007, 60.028090000000006],
          ["z"],
        ],
      },
      {
        type: "textbox",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 236.5,
        top: 267.18,
        width: 283.45,
        height: 74.58,
        fill: "#ffffff",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        text: "sample",
        fontSize: "66",
        fontWeight: 400,
        fontFamily: "Gugi",
        fontStyle: "normal",
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "left",
        textBackgroundColor: "",
        charSpacing: 0,
        path: null,
        minWidth: 20,
        splitByGrapheme: false,
        customType: "textbox",
        styles: {},
      },
      {
        type: "path",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 411.67,
        top: 247.41,
        width: 191,
        height: 167.13,
        fill: "#ff0000",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 0.68,
        scaleY: 0.68,
        angle: 179.65,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        customType: "shape",
        path: [
          ["M", 4.4475, 186.66062],
          ["L", 99.9475, 19.535619999999994],
          ["L", 195.4475, 186.66062],
          ["L", 4.447509999999994, 186.66062],
          ["z"],
        ],
      },
    ],
    background: "white",
  },
  {
    version: "4.4.0",
    objects: [
      {
        type: "path",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 220.98,
        top: 211.24,
        width: 182,
        height: 182,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 0.78,
        scaleY: 0.78,
        angle: 89.85,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        customType: "shape",
        path: [
          ["M", 10.4675, 193.4375],
          ["L", 10.4675, 11.4375],
          ["L", 192.46738, 193.4375],
          ["L", 10.467500000000001, 193.4375],
          ["z"],
        ],
      },
      {
        type: "path",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 485.1,
        top: 353.1,
        width: 182,
        height: 182,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 0.78,
        scaleY: 0.78,
        angle: -89.99,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        customType: "shape",
        path: [
          ["M", 10.4675, 193.4375],
          ["L", 10.4675, 11.4375],
          ["L", 192.46738, 193.4375],
          ["L", 10.467500000000001, 193.4375],
          ["z"],
        ],
      },
      {
        type: "textbox",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 252.41,
        top: 251.54,
        width: 179.45,
        height: 45.2,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1.42,
        scaleY: 1.42,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        text: "sample",
        fontSize: "40",
        fontWeight: "500",
        fontFamily: "Sunflower",
        fontStyle: "normal",
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "left",
        textBackgroundColor: "",
        charSpacing: 0,
        path: null,
        minWidth: 20,
        splitByGrapheme: false,
        customType: "textbox",
        styles: {},
      },
    ],
    background: "white",
  },
  {
    version: "4.4.0",
    objects: [
      {
        type: "ellipse",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 102,
        top: 162,
        width: 200,
        height: 200,
        fill: "Black",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1.25,
        scaleY: 1.25,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        rx: 100,
        ry: 100,
        customType: "shape",
      },
      {
        type: "ellipse",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 138,
        top: 152,
        width: 200,
        height: 200,
        fill: "#ffffff",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1.17,
        scaleY: 1.17,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        rx: 100,
        ry: 100,
        customType: "shape",
      },
      {
        type: "textbox",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 236.75,
        top: 202.96,
        width: 423.2,
        height: 113,
        fill: "#0d0000",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        text: "sample",
        fontSize: "100",
        fontWeight: 400,
        fontFamily: "Sunflower",
        fontStyle: "normal",
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "left",
        textBackgroundColor: "",
        charSpacing: 0,
        path: null,
        minWidth: 20,
        splitByGrapheme: false,
        customType: "textbox",
        styles: {},
      },
    ],
    background: "white",
  },
  {
    version: "4.4.0",
    objects: [
      {
        type: "ellipse",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 65,
        top: 138,
        width: 200,
        height: 200,
        fill: "#ebde29",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1.36,
        scaleY: 1.36,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        rx: 100,
        ry: 100,
        customType: "shape",
      },
      {
        type: "ellipse",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 199.5,
        top: 235.5,
        width: 200,
        height: 200,
        fill: "#ffffff",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1.36,
        scaleY: 1.36,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        rx: 100,
        ry: 100,
        customType: "shape",
      },
      {
        type: "ellipse",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: -68.5,
        top: 236.5,
        width: 200,
        height: 200,
        fill: "#ffffff",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1.36,
        scaleY: 1.36,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        rx: 100,
        ry: 100,
        customType: "shape",
      },
      {
        type: "rect",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 65.5,
        top: 361.5,
        width: 200,
        height: 200,
        fill: "#ffffff",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1.36,
        scaleY: 1.36,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        rx: 0,
        ry: 0,
        customType: "shape",
      },
      {
        type: "textbox",
        version: "4.4.0",
        originX: "left",
        originY: "top",
        left: 322,
        top: 227.18,
        width: 290.28,
        height: 110.74,
        fill: "#ebde29",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        text: "sample",
        fontSize: "98",
        fontWeight: 400,
        fontFamily: "Gamja Flower",
        fontStyle: "normal",
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "left",
        textBackgroundColor: "",
        charSpacing: 0,
        path: null,
        minWidth: 20,
        splitByGrapheme: false,
        customType: "textbox",
        styles: {},
      },
    ],
    background: "white",
  },
];
